import h5py
import numpy as np
import faiss
from tqdm import tqdm
from pathlib import Path
from argparse import ArgumentParser


# DISCLAIMER: Code originally generated by AI and slightly modified
def main():
    parser = ArgumentParser()
    parser.add_argument("--input-dataset", default="./data/laion2B-en-clip768v2-n=10M.h5", type=Path)
    parser.add_argument("--queries", default="./data/public-queries-2024-laion2B-en-clip768v2-n=10k.h5", type=Path)
    parser.add_argument("--subset-size", default=1_000_000, type=int)
    parser.add_argument("--k", default=100, type=int)
    parser.add_argument("--chunk-size", default=100_000, type=int)
    parser.add_argument("--seed", default=42, type=int)
    args = parser.parse_args()

    np.random.seed(args.seed)

    with h5py.File(args.input_dataset, "r") as f:
        n_data, dim = f["emb"].shape

    print(f"Input dataset: {n_data:,} × {dim}")
    print(f"Subset size:   {args.subset_size:,}")

    subset_indices = np.random.choice(
        n_data, size=args.subset_size, replace=False
    )
    subset_indices.sort()

    subset_file = Path(f"laion2B-en-clip768v2-n={args.subset_size//1_000_000}M.h5")

    with h5py.File(subset_file, "w") as fout:
        emb_out = fout.create_dataset(
            "emb",
            shape=(args.subset_size, dim),
            dtype=np.float32
        )

        with h5py.File(args.input_dataset, "r") as fin:
            emb_in = fin["emb"]

            for start in tqdm(range(0, args.subset_size, args.chunk_size),
                              desc="Creating subset"):
                end = min(start + args.chunk_size, args.subset_size)
                idx = subset_indices[start:end]
                emb_out[start:end] = emb_in[idx]

    print(f"Saved subset dataset to: {subset_file}")

    with h5py.File(args.queries, "r") as f:
        queries = f["emb"][:].astype("float32")

    print("Loading subset into memory for GT computation...")
    with h5py.File(subset_file, "r") as f:
        data = f["emb"][:].astype("float32")

    print("Building FAISS IndexFlatIP...")
    index = faiss.IndexFlatIP(dim)
    index.add(data)

    print("Computing ground truth...")
    _, knns = index.search(queries, args.k)

    gt_file = Path(
        f"gold-standard-dbsize={args.subset_size//1_000_000}M"
        "--public-queries-2024-laion2B-en-clip768v2-n=10k.h5"
    )

    with h5py.File(gt_file, "w") as f:
        f.create_dataset("knns", data=knns.astype(np.int32))

    print(f"Saved ground truth to: {gt_file}")


if __name__ == "__main__":
    main()
